// AUTH
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// DEPARTMENTS
export const ALL_DEPARTMENTS_LOADED = 'ALL_DEPARTMENTS_LOADED';
export const DEPARTMENT_LOADED = 'DEPARTMENT_LOADED';
export const DEPARTMENT_CREATED = 'DEPARTMENT_CREATED';
export const DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED';
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR';

// PROGRAMS
export const ALL_PROGRAMS_LOADED = 'ALL_PROGRAMS_LOADED';
export const PROGRAM_LOADED = 'PROGRAM_LOADED';
export const PROGRAM_CREATED = 'PROGRAM_CREATED';
export const PROGRAM_UPDATED = 'PROGRAM_UPDATED';
export const PROGRAM_ERROR = 'PROGRAM_ERROR';

// COORDINATOR
export const ALL_COORDINATORS_LOADED = 'ALL_COORDINATORS_LOADED';
export const COORDINATOR_LOADED = 'COORDINATOR_LOADED';
export const COORDINATOR_REGISTER_SUCCESS = 'COORDINATOR_REGISTER_SUCCESS';
export const COORDINATOR_REGISTER_FAILED = 'COORDINATOR_REGISTER_FAILED';
export const COORDINATORS_ERROR = 'COORDINATOR_ERROR';
export const COORDINATOR_NAME_UPDATED = 'COORDINATOR_NAME_UPDATED';
export const COORDINATOR_PASSWORD_UPDATED = 'COORDINATOR_PASSWORD_UPDATED';
export const COORDINATOR_PROFILE_PICTURE_UPDATED =
  'COORDINATOR_PROFILE_PICTURE_UPDATED';
export const COORDINATOR_PROFILE_PICTURE_REMOVED =
  'COORDINATOR_PROFILE_PICTURE_REMOVED';
export const SET_AUTH_COORDINATOR_LOADING = 'SET_AUTH_COORDINATOR_LOADING';
export const UNSET_AUTH_COORDINATOR_LOADING = 'UNSET_AUTH_COORDINATOR_LOADING';

// APPLICANTS
export const APPLICANT_LOADED = 'APPLICANT_LOADED';
export const APPLICANT_PERSONAL_DETAILS_UPDATED =
  'APPLICANT_PERSONAL_DETAILS_UPDATED';
export const APPLICANT_INCOME_DETAILS_UPDATED =
  'APPLICANT_INCOME_DETAILS_UPDATED';
export const APPLICANT_ERROR = 'APPLICANT_ERROR';


//SURVEY
export const SURVEY_GET_SUCCESS = 'SURVEY_SUCCESS';
export const SURVEY_GET_FAILURE = 'SURVEY_FAILURE';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const SURVEY_RESPONSE_SUCCESS = 'SURVEY_RESPONSE_SUCCESS';
export const SURVEY_RESPONSE_FAIL = 'SURVEY_RESPONSE_FAIL';
export const GET_SURVEY_RESP_SUCCESS = 'GET_SURVEY_RESP_SUCCESS';
export const GET_SURVEY_RESP_FAIL = 'GET_SURVEY_RESP_FAIL';
export const SET_SURVEY_DATES_SUCCESS = 'SET_SURVEY_DATES_SUCCESS';
export const SET_SURVEY_DATES_FAIL = 'SET_SURVEY_DATES_FAIL';